# defaults:
#   - _self_
#   - override hydra/job_logging: disabled
#   - override hydra/hydra_logging: disabled

# wandb:
#   project: "cv-team9"
#   entity: "12hongcoffee-42"
#   name: "HELL-TRAIN-${model.name}-sz${data.image_size}"

# train:
#   seed: 42
#   num_epochs: 20 # '지옥 훈련'은 더 오래 해야 함
#   learning_rate: 3e-4 # 안정적인 시작

# data:
#   path: "./data/raw"
#   image_size: 384 # 384 사이즈로 시작
#   batch_size: 16
#   num_workers: 4
#   augmentation_level: "ultimate" # [핵심] '궁극의 증강' 사용

# model:
#   name: "convnext_base" # '지옥 훈련'을 받을 우리의 에이스
#   num_classes: 17

# configs/config.yaml (Ultimate Training용)

defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

wandb:
  project: "cv-team9"
  entity: "12hongcoffee-42"
  name: "ULTIMATE-TRAIN-${model.name}-sz${data.image_size}"

train:
  seed: 42
  num_epochs: 30 # 강력한 증강 데이터는 더 오래 학습해야 함
  learning_rate: 3e-4 # 안정적인 시작

data:
  path: "./data/augmented_v1_0707/"
  image_size: 384
  batch_size: 16
  num_workers: 4
  augmentation_level: "base" # 이미 증강된 데이터이므로, 학습 시에는 기본 변환만 적용

model:
  name: "convnext_base" # '지옥 훈련'을 받을 우리의 에이스
  num_classes: 17