# # 1. 기본값 설정
# defaults:
#   - _self_
#   - model: effnet_b2
#   - data: size384
#   - override hydra/job_logging: disabled
#   - override hydra/hydra_logging: disabled

# # 2. 완디비 설정
# wandb:
#   project: "cv-team9"
#   entity: "12hongcoffee-42"
#   name: "${model.name}-sz${data.image_size}-lr_${train.learning_rate}"

# # 3. 공통 학습 파라미터
# train:
#   seed: 42
#   num_epochs: 10 # 시간 내에 끝나도록 에폭 조절
#   learning_rate: 1e-3 # 기본값

# # 4. 모델 설정
# model:
#   num_classes: 17

# # 5. Hydra Sweeper 설정 (자동화 실험의 핵심)
# hydra:
#   sweeper:
#     # params: 실험할 모든 조합을 지시
#     params:
#       model: effnet_b1, effnet_b2, tf_efficientnetv2_s
#       data: size384, size512
#       train.learning_rate: 1e-4, 3e-4


# 버전2 
# configs/config.yaml

# 기본값 설정
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# 완디비 설정
wandb:
  project: "cv-team9"
  entity: "12hongcoffee-42"
  name: "CHAMPION-RUN-${model.name}-sz${data.image_size}"

# 공통 학습 파라미터
train:
  seed: 42
  num_epochs: 25      # 챔피언 모델이니 25 에폭으로 충분히 학습
  learning_rate: 3e-4 # 챔피언 학습률

# 데이터 설정
data:
  path: "./data/raw"
  image_size: 512     # 챔피언 이미지 크기
  batch_size: 8       # 512 사이즈에 맞는 배치 크기
  num_workers: 4
  augmentation_level: "strong" # 챔피언 증강 레벨

# 모델 설정
model:
  name: "tf_efficientnetv2_s" # 최종 챔피언 모델
  num_classes: 17